name = "FancyDebugger"
uuid = "5f537d45-e442-4808-b901-5186814effc6"
authors = ["Valentin Churavy <v.churavy@gmail.com>"]
version = "0.1.0"

[deps]
Debugger = "31a5f54b-26ea-5ae9-a837-f05ce5417438"
GPUCompiler = "61eb1bfa-7361-4325-ad38-22787b887f55"

[compat]
Debugger = "0.7"
GPUCompiler = "0.16"
julia = "1.9"
